source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AirPlay_Example', :exclusive => true do
  pod "AirPlay", :path => "../"
end

target 'AirPlay_Tests', :exclusive => true do
  pod "AirPlay", :path => "../"

  
end
